# Generated by Django 4.2.7 on 2024-02-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='userImages/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('orders_made', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
