# Generated by Django 4.2.7 on 2024-01-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(default='../static/media/logoTTTransp1.png', upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('releaseDate', models.DateField(blank=True, null=True)),
                ('currentStock', models.PositiveIntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('defaultFeaturedStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('featuredPromOverlay', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
