# Generated by Django 4.2.7 on 2024-02-13 05:37

import ItemsApp.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ItemsApp.models.product_image_upload_handler)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('manufacturer', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('featured_status', models.BooleanField(blank=True, default=False, null=True)),
                ('featured_promo_overlay', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
