# Generated by Django 4.2.7 on 2024-01-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelproduct',
            old_name='defaultFeaturedStatus',
            new_name='featuredStatus',
        ),
    ]
