# Generated by Django 4.2.7 on 2024-01-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0002_rename_defaultfeaturedstatus_modelproduct_featuredstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelproduct',
            old_name='featuredPromOverlay',
            new_name='featuredPromoOverlay',
        ),
    ]
