# Generated by Django 4.2.7 on 2024-01-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0003_rename_featuredpromoverlay_modelproduct_featuredpromooverlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(default='/static/media/logoTT_sample2.webp', upload_to=''),
        ),
    ]
