# Generated by Django 4.2.7 on 2024-02-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0003_alter_modelcategory_sourcecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='ItemsApp.modelcategory'),
        ),
        migrations.AlterField(
            model_name='modelproduct',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, null=True, to='ItemsApp.modelmanufacturer'),
        ),
    ]
