# Generated by Django 4.2.7 on 2024-02-23 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0006_alter_modelcategory_sourcecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ItemsApp.modelcategory'),
        ),
    ]
