# Generated by Django 4.2.7 on 2024-01-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0006_alter_modelproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(upload_to='productImages/'),
        ),
    ]
