# Generated by Django 4.2.7 on 2024-01-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0007_alter_modelproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(height_field=256, upload_to='productImages/', width_field=256),
        ),
    ]
