# Generated by Django 4.2.7 on 2024-02-23 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0007_remove_modelproduct_category_modelproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelproduct',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='modelproduct',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ItemsApp.modelmanufacturer'),
        ),
    ]
