# Generated by Django 4.2.7 on 2024-01-25 09:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0010_alter_modelproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
