# Generated by Django 4.2.7 on 2024-01-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0011_alter_modelproduct_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelproduct',
            old_name='currentStock',
            new_name='current_stock',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='featuredPromoOverlay',
            new_name='featured_promo_overlay',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='featuredStatus',
            new_name='featured_status',
        ),
        migrations.RenameField(
            model_name='modelproduct',
            old_name='releaseDate',
            new_name='release_date',
        ),
    ]
