# Generated by Django 4.2.7 on 2024-02-06 10:00

import ItemsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ItemsApp', '0012_rename_currentstock_modelproduct_current_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=ItemsApp.models.product_image_upload_handler),
        ),
    ]
